baseURL: https://smirlwebs.com/
languageCode: en-us
title: Alex Williams - smirlwebs.com
theme: roxo

disableKinds: ["taxonomy", "taxonomyTerm"]
author:
  name: "Alex Williams"

params:
  banner:
    enable: true
    background_color: "#6fcdbd"

  footer:
    sitemap:
      title: "Sitemap"
      link:
        - name: Home
          url: /
        - name: Blog
          url: /blog/

    social:
      title: Social Media
      link:
        - icon: "github"
          iconset: fa
          name: "Github"
          url: "https://github.com/smirl"

        - icon: "instagram"
          iconset: fa
          name: "Instagram"
          url: "https://www.instagram.com/smirlie/"

        - icon: "linkedin"
          iconset: fa
          name: "LinkedIn"
          url: "https://www.linkedin.com/in/alexander-williams-5aa36761/"

        - icon: "graduation-cap"
          iconset: "fa"
          name: "Google Scholar"
          url: "https://scholar.google.com/citations?hl=en&user=aAw2Qe4AAAAJ"

    service:
      title: made with ❤️
      description: always opensource

pygmentsCodeFences: true
pygmentsStyle: dracula
