baseURL: http://smirlwebs.com/
languageCode: en-us
title: Alex Williams - smirlwebs.com
theme: roxo

disableKinds: ["taxonomy", "taxonomyTerm"]
author:
  name: "Alex Williams"

menu:
  nav:
    - identifier: home
      name: Home
      url: /
    # - identifier: blog
    #   name: Blog
    #   url: /blog/

params:
  banner:
    enable: true
    background_color: "#6fcdbd"

  footer:
    sitemap:
      title: "Sitemap"
      link:
        - name: Home
          url: /
        # - name: Blog
        #   url: /blog/

    social:
      title: Social Media
      link:
        - icon: "github"
          name: "Github"
          url: "https://github.com/smirl"

        - icon: "instagram"
          name: "Instagram"
          url: "https://www.instagram.com/smirlie/"

        - icon: "linkedin"
          name: "LinkedIn"
          url: "https://www.linkedin.com/in/alexander-williams-5aa36761/"

        - iconorigin: "ai"
          iconset: "ai"
          icon: "google-scholar"
          name: "Google Scholar"
          url: "https://scholar.google.com/citations?hl=en&user=aAw2Qe4AAAAJ"

    service:
      title: ""
      description: made with ❤️
